import type { PortalBootstrapPayload } from '@/integrations/nui/nui.types'

export const mockPortalBootstrap: PortalBootstrapPayload = {
    profile: {
        characterName: 'Marcus Reed',
        bankBalance: 328750,
        ownsBusiness: false,
        investorProgress: {
            points: 1840,
            rank: 'Verified Investor',
            currentRankPoints: 1750,
            nextRankPoints: 2750,
            percentage: 9,
        },
    },

    tiers: [
        {
            tierNumber: 1,
            businessType: 'coffee_shop',
            displayName: 'Coffee Shop',
            requiredInvestorScore: 0,
            purchasePrice: 15000,
            projectedRevenue: 3000,
            operatingFeePercentage: 25,
            isUnlocked: true,
            availableLocationCount: 18,
            totalLocationCount: 21,
        },
        {
            tierNumber: 2,
            businessType: 'gas_station',
            displayName: 'Gas Station',
            requiredInvestorScore: 500,
            purchasePrice: 25000,
            projectedRevenue: 6000,
            operatingFeePercentage: 23,
            isUnlocked: true,
            availableLocationCount: 20,
            totalLocationCount: 24,
        },
        {
            tierNumber: 3,
            businessType: 'restaurant',
            displayName: 'Restaurant',
            requiredInvestorScore: 1500,
            purchasePrice: 40000,
            projectedRevenue: 10000,
            operatingFeePercentage: 22,
            isUnlocked: true,
            availableLocationCount: 17,
            totalLocationCount: 22,
        },
        {
            tierNumber: 4,
            businessType: 'laundromat',
            displayName: 'Laundromat',
            requiredInvestorScore: 2750,
            purchasePrice: 55000,
            projectedRevenue: 15000,
            operatingFeePercentage: 21,
            isUnlocked: false,
            availableLocationCount: 0,
            totalLocationCount: 9,
        },
        {
            tierNumber: 5,
            businessType: 'bar',
            displayName: 'Bar',
            requiredInvestorScore: 4000,
            purchasePrice: 75000,
            projectedRevenue: 22000,
            operatingFeePercentage: 20,
            isUnlocked: false,
            availableLocationCount: 0,
            totalLocationCount: 8,
        },
        {
            tierNumber: 6,
            businessType: 'nightclub',
            displayName: 'Nightclub',
            requiredInvestorScore: 5500,
            purchasePrice: 100000,
            projectedRevenue: 32000,
            operatingFeePercentage: 19,
            isUnlocked: false,
            availableLocationCount: 0,
            totalLocationCount: 5,
        },
        {
            tierNumber: 7,
            businessType: 'stripclub',
            displayName: 'Strip Club',
            requiredInvestorScore: 7500,
            purchasePrice: 150000,
            projectedRevenue: 45000,
            operatingFeePercentage: 18,
            isUnlocked: false,
            availableLocationCount: 0,
            totalLocationCount: 4,
        },
        {
            tierNumber: 8,
            businessType: 'carwash',
            displayName: 'Car Wash',
            requiredInvestorScore: 10000,
            purchasePrice: 250000,
            projectedRevenue: 65000,
            operatingFeePercentage: 17,
            isUnlocked: false,
            availableLocationCount: 0,
            totalLocationCount: 2,
        },
        {
            tierNumber: 9,
            businessType: 'casino',
            displayName: 'Casino',
            requiredInvestorScore: 15000,
            purchasePrice: 750000,
            projectedRevenue: 100000,
            operatingFeePercentage: 15,
            isUnlocked: false,
            availableLocationCount: 0,
            totalLocationCount: 1,
        },
    ],

    locations: [
        {
            key: 'coffee_shop:1',
            locationId: 1,
            ownedBusinessId: null,
            businessType: 'coffee_shop',
            displayName: 'Bean Machine',
            imageFileName: null,
            price: 15000,
            ownership: 'available',
            coordinates: {
                x: -836.874695,
                y: -609.50769,
                z: 29.010254,
            },
            address: {
                street: 'North Rockford Drive',
                crossingRoad: null,
                zone: 'Little Seoul',
            },
        },
        {
            key: 'coffee_shop:2',
            locationId: 2,
            ownedBusinessId: null,
            businessType: 'coffee_shop',
            displayName: 'Bean Machine',
            imageFileName: null,
            price: 17500,
            ownership: 'available',
            coordinates: {
                x: -1368.092285,
                y: -207.679123,
                z: 44.512085,
            },
            address: {
                street: 'Cougar Avenue',
                crossingRoad: 'Morningwood Boulevard',
                zone: 'Morningwood',
            },
        },
        {
            key: 'coffee_shop:3',
            locationId: 3,
            ownedBusinessId: null,
            businessType: 'coffee_shop',
            displayName: 'Bean Machine',
            imageFileName: null,
            price: 15000,
            ownership: 'available',
            coordinates: {
                x: -689.208801,
                y: -854.716492,
                z: 23.820557,
            },
            address: {
                street: 'Palomino Avenue',
                crossingRoad: null,
                zone: 'Little Seoul',
            },
        },
        {
            key: 'coffee_shop:17',
            locationId: 17,
            ownedBusinessId: null,
            businessType: 'coffee_shop',
            displayName: 'Cool Beans',
            imageFileName: null,
            price: 15000,
            ownership: 'available',
            coordinates: {
                x: -1280.610962,
                y: -875.261536,
                z: 11.924561,
            },
            address: {
                street: 'Bay City Avenue',
                crossingRoad: null,
                zone: 'Del Perro',
            },
        },
    ],

    settings: {
        currencySymbol: '$',
        theme: {
            AccentColor: '#2f81f7',
            AccentHoverColor: '#4b93f8',
            AccentDarkColor: '#1f6fd8',
            AccentSoftColor: 'rgba(47, 129, 247, 0.14)',
            BodyColor: '#0b1118',
            PanelColor: '#111923',
            PanelAltColor: '#16212d',
            CardColor: '#1a2735',
            BorderColor: '#26384a',
            BorderSoftColor: '#33485d',
            TextColor: '#f3f7fb',
            MutedTextColor: '#91a3b7',
            SuccessColor: '#22a06b',
            WarningColor: '#d6a332',
            DangerColor: '#d9534f',
        },
    },

    localization: {
        locale: 'en',
        messages: {
            common: {
                close: 'Close',
                cancel: 'Cancel',
                confirm: 'Confirm',
                loading: 'Loading…',
            },
            portal: {
                header: {
                    city: 'Los Santos',
                    portalName: 'Business Portal',
                    exchangeName: 'Commercial Property Exchange',
                    tagline: 'Legitimate opportunities. Real returns.',
                    investor: 'Investor',
                    bankBalance: 'Bank Balance',
                    investorScore: 'Investor Score',
                    investorScoreProgress: 'Progress toward the next investor rank',
                    scorePoints: '{points} pts',
                    scoreProgressValue: '{current} / {next} pts',
                },
                tierSelector: {
                    ariaLabel: 'Business tiers',
                    tier: 'Tier {number}',
                    requiredScore: '{score} pts required',
                    scoreRequirement: '{score} pts',
                    available: 'Available',
                    locked: 'Locked',
                },
            },
        },
    },
}