--- DEV TOOL - not required for production use.
--- Collects vending machine coordinates reported by the client-side scanner, dedupes them,
--- and exports a ready-to-use shared/business_locations_vending.lua file to disk.
--- Remove or disable this folder before shipping to a live server.

local CollectedVending = {} -- { {id, x, y, z}, ... }
local nextId = 1

--- Checks whether the given coordinates are already known (within a small tolerance).
--- @param coords vector3
--- @return boolean
local function IsAlreadyKnown(coords)
    for _, entry in ipairs(CollectedVending) do
        local dist = #(vector3(entry.x, entry.y, entry.z) - coords)
        if dist < 3.0 then
            return true
        end
    end
    return false
end

--- Event: client reports a discovered vending machine location.
--- Restricted to admins only, since this is a dev-only setup tool.
RegisterServerEvent("t1ger_moneywash:devtools:reportVendingMachine")
AddEventHandler("t1ger_moneywash:devtools:reportVendingMachine", function(coords)
    local src = source

    if not _API.Player.isAdmin(src) then return end
    if type(coords) ~= "vector3" then return end
    if IsAlreadyKnown(coords) then return end

    table.insert(CollectedVending, {id = nextId, x = coords.x, y = coords.y, z = coords.z})
    nextId = nextId + 1

    print(("[DevTool] New vending machine recorded (#%d) at %.2f, %.2f, %.2f - total: %d"):format(
        nextId - 1, coords.x, coords.y, coords.z, #CollectedVending
    ))
end)

--- Generates the Lua file content for the collected vending machine locations.
--- @return string
local function BuildExportContent()
    local lines = {}
    table.insert(lines, "-- Auto-generated by devtools vending scan. Review before using in production.")
    table.insert(lines, "return {")
    table.insert(lines, "    vending = {")

    for _, entry in ipairs(CollectedVending) do
        table.insert(lines, string.format(
            "        {id = %d, coords = vector3(%.2f, %.2f, %.2f)},",
            entry.id, entry.x, entry.y, entry.z
        ))
    end

    table.insert(lines, "    }")
    table.insert(lines, "}")

    return table.concat(lines, "\n")
end

--- Console/admin command: writes the collected locations directly to disk as a Lua file.
RegisterCommand("exportvending", function(src)
    if src ~= 0 and not _API.Player.isAdmin(src) then return end

    if #CollectedVending == 0 then
        print("[DevTool] No vending machines collected yet - run /vendscan on the client first.")
        return
    end

    local content = BuildExportContent()
    local ok = SaveResourceFile(GetCurrentResourceName(), "shared/business_locations_vending_export.lua", content, -1)

    if ok then
        print(("[DevTool] Exported %d vending machine locations to shared/business_locations_vending_export.lua"):format(#CollectedVending))
    else
        print("[DevTool] Failed to write export file - check file permissions/resource path.")
    end
end, true) -- restricted = true, console/ACE only by default

--- Console/admin command: clears all collected locations (start over).
RegisterCommand("clearvendingscan", function(src)
    if src ~= 0 and not _API.Player.isAdmin(src) then return end

    CollectedVending = {}
    nextId = 1
    print("[DevTool] Cleared all collected vending machine locations.")
end, true)